baseURL = "https://ciatastrophe.netlify.com"
languageCode = "en-us"
title = "Anastasia üíª"
theme = "minimal"
disqusShortname = "https-ciatastrophe-netlify-com"
googleAnalytics = ""

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"

rssLimit = 10

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[params]
    author = "Anastasia Kaloudi"
    description = "| My HolidayCheck Apprenticeship Blog - Stay Tuned! "
    githubUsername = "#ciaskious"
    accent = "pink"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "solarized-dark"
    highlightLanguages = ["python", "scala"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 2

[[menu.main]]
name = ‚ÄúRSS‚Äù
weight = 99
identifier = ‚Äúrss‚Äù
url = ‚Äú/feed.xml‚Äù


# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/


[[menu.icon]]
    url = "https://github.com/ciaskious/"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/anaskaloudi/"
    name = "twitter"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/anastasia-kaloudi93/"
    name = "linkedin"
    weight = 3
